restore-yarn-cache: &restore-yarn-cache
  restore_cache:
    keys:
      - v1-{{ checksum "yarn.lock" }}

npmrc: &npmrc
  run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - *restore-yarn-cache
      - *npmrc
      - run: yarn
      - run: yarn build
      - run: git config user.email "ovotech-ci@ovoenergy.com"
      - run: git config user.name "Ovotech CI"
      - run: yarn publish --new-version $CIRCLE_TAG

  test:
    docker:
      - image: circleci/node:16
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_PASSWORD: dev-pass
    steps:
      - checkout
      - *restore-yarn-cache
      - *npmrc
      - run: yarn config set yarn-offline-mirror ~/.cache/yarn
      - run: yarn
      - run: yarn build
      - run: mkdir -p reports/junit
      - run: yarn lint:prettier
      - run: yarn lint:eslint --format junit -o reports/junit/js-lint-results.xml
      - run:
          command: yarn test --runInBand --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
      - store_test_results:
          path: reports/junit
      - save_cache:
          key: v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
  test:
    jobs:
      - test
